### ISSUE TITLE
中途要输入github token是什么？

### ISSUE THREAD

**Issue by gimgoo** [V2RaySSR/Trojan_Panel#2]
中途要输入github token是什么？不输入没法继续执行，read me能否更新下怎么使用？

**Comment by V2RaySSR** [comment]
那是因为，你composer install的次数太多了，你需要搜索。。github token ，然后创建一个TOKEN

**Comment by gimgoo** [comment]
github的token有很多权限选项，而且这个脚本使用的时候，都没有输入过我自己的github账号，请问输我账号的github token作用在哪啊？

**Comment by V2RaySSR** [comment]
因为composer install是GITHUB的程序。你安装次数过多，然后GITHUB怕浪费系统资源，需要输入TOKEN，不然成千上万次的重复安装，不是吧GITHUB服务器都搞奔溃了吗？然后GITHUB的权限，你只需要那个GIGS吧。

**Comment by V2RaySSR** [comment]
我昨天重复安装，如今同一个IP再次安装，我也是需要输入TOKEN的

**Comment by V2RaySSR** [comment]
你换一个VPS就OK了

**Comment by gimgoo** [comment]
好的，我试试，谢谢

**Comment by yumetec** [comment]
安装后没法访问的，安装期间也出现在问题了，而且debian9安装最新的trojan运行不了的。

**Comment by gimgoo** [comment]
我也是这样，换成debian10也没成功，更换过IP了也是那样

> 安装后没法访问的，安装期间也出现在问题了，而且debian9安装最新的trojan运行不了的。
